# Generated by Django 5.1 on 2024-08-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.TextField(blank=True, max_length=64, null=True, verbose_name='Адрес транзакции')),
                ('owner_address', models.CharField(max_length=64, verbose_name='Адрес владельца')),
                ('unique_hash', models.CharField(max_length=20, unique=True, verbose_name='Хеш токена')),
                ('media_url', models.URLField(verbose_name='Ссылка на медиа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'NFT Токен',
                'verbose_name_plural': 'NFT Токены',
                'db_table': 'crypto_token',
                'abstract': False,
            },
        ),
    ]
